Comenzamos importando las librerias que vamos a utilizar para llevar a cabo el modelo.

## **Supervised techniques**

In [9]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline 
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier

## **Importing data from a dataset**

In [10]:
import os
os.getcwd()

'C:\\Users\\vsanc\\Documents\\KNN_LaSalle_Big_Data'

A continuación damos la orden para que lea el archivo csv que es el dataframe.

En el código que detallo a coninuación, en la primera liena estamos pidiendo a la máquina que: 
('**ARCHIVO.CSV**, **ecoding** para representar caracteres **='utf-8'** significa que los caracteres comunes se representan con menos bytes, lo que ahorra espacio, **sep=','** se utiliza para especificar el carácter que se utilizará como separador de columnas en el archivo CSV. en este caso es una coma)

In [17]:
mnist_train = pd.read_csv('./mnist_train.csv', encoding='utf-8', sep=',')
mnist_train.head(9)

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
mnist_test = pd.read_csv('./mnist_test.csv', encoding='utf-8', sep=',')
mnist_test.head(9)

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## **Machine Learning** | Entrenamos el modelo

Vamos a dividir el conjunto de datos en dos partes: conjunto de características y etiqueta de destino

In [5]:
feature_train = mnist_train.loc[:,mnist_train.columns !='label']
target_train = mnist_train.label

In [6]:
feature_test = mnist_test.loc[:,mnist_test.columns !='label']
target_test = mnist_test.label

**K-Nearest Neighbors Classification**

In [11]:
# Create a KNN classifier object
knn = KNeighborsClassifier(n_neighbors=2)
 
# Train the model using the training dataset
knn.fit(feature_train,target_train)
 
# Predict the target variable for test dataset
predictions_knn = knn.predict(feature_test)

In [12]:
predictions_knn

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [13]:
# Import metrics module for performance evaluation
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
 
# Calculate model accuracy
print("Accuracy:",accuracy_score(target_test, predictions_knn))

Accuracy: 0.9627

In [14]:
# Calculate model precision
print("Precision:",precision_score(target_test, predictions_knn, average='micro'))
# Calculate model recall
print("Sensitivity/Recall:",recall_score(target_test, predictions_knn, average='micro'))
# Calculate model f1 score
print("F1-Score:",f1_score(target_test, predictions_knn, average='micro'))

Precision: 0.9627
Sensitivity/Recall: 0.9627
F1-Score: 0.9627

## **Implementamos el modelo

In [15]:
n_csv = pd.read_csv('./n.csv', encoding='utf-8', sep=';')
n_csv.head(9)

,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,1x10,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
knn.predict(n_csv)

array([7], dtype=int64)